### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by unnc-wqw** [Jia-Research-Lab/MASA-SR#18]
Hi. I'm confused that why the test results are not ideal as I get started and train by following the readme tutorial.
![000_0](https://user-images.githubusercontent.com/66479982/148747086-78cf68fc-5412-4fb8-a76a-e7f9578fa1c1.png)
![003_0](https://user-images.githubusercontent.com/66479982/148747215-0fea41f8-656e-40cf-a7b8-e6aea5a119ca.png)
Thanks!

**Comment by SkyeLu** [comment]
Hi, as mentioned in https://github.com/dvlab-research/MASA-SR/issues/1#issue-900661080, not all the results are satisfying, especially on the hunman faces.

**Comment by unnc-wqw** [comment]
Fine, thanks!
