### ISSUE TITLE
SR_scale=2 has problems

### ISSUE THREAD

**Issue by xianrui-luo** [Jia-Research-Lab/MASA-SR#20]
Hi, when i set the sr_scale from 4 to 2, there would be an error:
RuntimeError: Caught RuntimeError in replica 0 on device 4. 
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED 

It is in MASA_arch.py", line 122,
 fea_L1 = self.blk_L1(self.act(self.conv_L1(x))) 
I wonder what is happening

**Comment by SkyeLu** [comment]
Hi, our model is only designed for x4 SR. If you want to test on x2 SR, the model architecture should be modified and retrained.

**Comment by xianrui-luo** [comment]
Thank you for replying.
