### ISSUE TITLE
Error : in MASA_arch.py 

### ISSUE THREAD

**Issue by jeonghomin** [Jia-Research-Lab/MASA-SR#24]
![image](https://user-images.githubusercontent.com/26131117/166967185-13a3ffc2-3729-4829-91b8-524425f41968.png)
RefSR/MASA-SR/models/archs/MASA_arch.py", line 435, in forward
    warp_ref_patches_x1 = warp_ref_patches_x1.view(N, C, H, W)
RuntimeError: shape '[1, 64, 228, 228]' is invalid for input of size 3211264

it keeps making error.. 

Do you know why this occurs?

**Comment by SkyeLu** [comment]
Are you testing on your own data? If so, the LR and Ref image should be padded if they are not multiples of a number (8/16/32..., depending on the value of the hyper-parameter 'window size').

**Comment by jeonghomin** [comment]
> ![image](https://user-images.githubusercontent.com/26131117/166967185-13a3ffc2-3729-4829-91b8-524425f41968.png) RefSR/MASA-SR/models/archs/MASA_arch.py", line 435, in forward warp_ref_patches_x1 = warp_ref_patches_x1.view(N, C, H, W) RuntimeError: shape '[1, 64, 228, 228]' is invalid for input of size 3211264
> 
> it keeps making error..
> 
> Do you kno
