### ISSUE TITLE
Does it work fine in scale 2 ? 

### ISSUE THREAD

**Issue by jeonghomin** [Jia-Research-Lab/MASA-SR#28]
When i change the args.sr_scale to 2, it makes error like this 
can you guys help me!
![image](https://user-images.githubusercontent.com/26131117/197971725-4645a43d-0662-4970-87e2-cbae60180fa3.png)

**Comment by SkyeLu** [comment]
Hi, please refer to this issue: #20

**Comment by LonglongaaaGo** [comment]
Hi @SkyeLu Thank you so much for your awesome repo and paper!
Could I ask a question about how to revise the codes if we want to work on scale=1 or scale=2?
Thank you so much！
